doctrine:
    dbal:
        # configure these for your database server
        # use postgresql for PostgreSQL
        # use sqlite for SQLite
        driver: 'mysql'
        server_version: '5.7'

        # only needed for MySQL
        charset: utf8mb4
        default_table_options:
            charset: utf8mb4
            collate: utf8mb4_unicode_ci

        url: '%env(resolve:DATABASE_URL)%'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        mappings:
#            App:
#                is_bundle: false
#                type: annotation
#                dir: '%kernel.project_dir%/src/Entity'
#                prefix: 'App\Entity'
#                alias: App
#            Article:
#                is_bundle: false
#                type: annotation
#                dir: '%kernel.project_dir%/src/PhpExample/Bundle/Article/Domain/Entity'
#                prefix: 'PhpLab\Sandbox\Article\Domain\Entities'
#                alias: App
            User:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/vendor/php7lab/sandbox/src/User/Domain/Entities'
                prefix: 'PhpLab\Sandbox\User\Domain\Entities'
                alias: App