fos_user:
    db_driver: orm # other valid values are 'mongodb' and 'couchdb'
    firewall_name: main
    user_class: PhpLab\Sandbox\User\Domain\Entities\User
    from_email:
        address: "vincent@vfac.fr"
        sender_name: "vincent@vfac.fr"