
# main page
default:
    path: /
    controller: App\Controller\MainController::index

app_rails:
    resource: "../../src/Bundle/Rails/Web/config/routes.yaml"

app_article:
    resource: "../../src/Bundle/Article/Api/config/routes.yaml"

app_user:
    resource: "../../src/Bundle/User/Api/config/routes.yaml"
