
auth_index:
    methods: [GET]
    path: /v1/auth
    controller: App\Bundle\User\Api\Controller\AuthController::index

auth_login:
    path: /v1/auth
    methods: [POST]
    controller: App\Bundle\User\Api\Controller\AuthController::login
