app_article_index:
    methods: [GET]
    path: /api/v1/article
    controller: App\Bundle\Article\Api\Controller\ArticleController::index

app_article_create:
    path: /api/v1/article
    methods: [POST]
    controller: App\Bundle\Article\Api\Controller\ArticleController::create

app_article_view:
    methods: [GET]
    path: /api/v1/article/{id}
    controller: App\Bundle\Article\Api\Controller\ArticleController::view
    requirements:
        id: '\d+'

app_article_update:
    methods: [PUT]
    path: /api/v1/article/{id}
    controller: App\Bundle\Article\Api\Controller\ArticleController::update
    requirements:
        id: '\d+'

app_article_delete:
    methods: [DELETE]
    path: /api/v1/article/{id}
    controller: App\Bundle\Article\Api\Controller\ArticleController::delete
    requirements:
        id: '\d+'

app_article_index_options:
    methods: [OPTIONS]
    path: /api/v1/article
    controller: App\Bundle\Article\Api\Controller\ArticleController::options

app_article_options:
    methods: [OPTIONS]
    path: /api/v1/article/{id}
    controller: App\Bundle\Article\Api\Controller\ArticleController::options
    requirements:
        id: '\d+'
